In [0]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
pd.set_option('display.max_columns', 130)
from sklearn import preprocessing
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import  classification_report
from imblearn.over_sampling import SMOTE, RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

In [0]:
le =preprocessing.LabelEncoder()
df=pd.read_csv("/content/drive/My Drive/maindataframe.csv")
dummpy_data_frame=df.copy()
df=df.iloc[:,1:31]
df.drop_duplicates(inplace=True)
y=df.ArrDel15.values
df.drop(["date","FlightDate","ArrTime","ArrDel15","ArrDelayMinutes"],axis=1,inplace=True)
df.Year=np.where(df.Year==2016,0,1)
df=pd.get_dummies(df,drop_first=True)
df["OriginAirportID"]=le.fit_transform(df.OriginAirportID)
df["DestAirportID"]=le.fit_transform(df.DestAirportID)
df["weatherCode"]=le.fit_transform(df.weatherCode)
df["cloudcover"]=le.fit_transform(df.cloudcover)





# New Section

In [17]:

x=df
x=x.values
df


Quarter  Year  Month  DayofMonth  DepTime  DepDel15  CRSDepTime  \
0              1     0      1           1    808.0       0.0         810   
1              1     0      1           1    810.0       0.0         812   
2              1     0      1           1    852.0       0.0         850   
3              1     0      1           1    900.0       0.0         855   
4              1     0      1           1    849.0       0.0         850   
...          ...   ...    ...         ...      ...       ...         ...   
1851431        4     1     12           2    456.0       0.0         504   
1851432        4     1     12           2    522.0       0.0         530   
1851433        4     1     12           2     54.0       0.0         104   
1851434        4     1     12          18    103.0       0.0         104   
1851435        4     1     12          17    110.0       0.0         104   

         DepDelayMinutes  OriginAirportID  DestAirportID  CRSArrTime  \
0                    0.0                0             10        1016   
1                    0.0                0              3         943   
2                    2.0                0              1        1009   
3                    5.0                0             10        1045   
4                    0.0                0              3        1016   
...                  ...              ...            ...         ...   
1851431              0.0               14              2         838   
1851432              0.0               14              5        1107   
1851433              0.0               14              5         638   
1851434              0.0               14              5         640   
1851435              6.0               14              5         640   

         windspeedKmph  winddirDegree  weatherCode  precipMM  visibility  \
0                   17            318            3       0.0          10   
1                   17            318            3       0.0          10   
2                   17            318            3       0.0          10   
3                   17            318            3       0.0          10   
4                   17            318            3       0.0          10   
...                ...            ...          ...       ...         ...   
1851431              5             20           11       0.0          10   
1851432              5             20           11       0.0          10   
1851433              4            159           11       0.0          10   
1851434              5             22            0       0.0          10   
1851435             15             13            0       0.0          10   

         pressure  cloudcover  DewPointF  WindGustKmph  tempF  WindChillF  \
0            1025         100         38            23     42          34   
1            1025         100         38            23     42          34   
2            1025         100         38            23     42          34   
3            1025         100         38            23     42          34   
4            1025         100         38            23     42          34   
...           ...         ...        ...           ...    ...         ...   
1851431      1017         100         47             8     48          47   
1851432      1017         100         47             8     48          47   
1851433      1017         100         49             7     50          50   
1851434      1020           1         47             9     60          60   
1851435      1016           0         27            38     50          46   

         humidity  time  loc_CLT  loc_DEN  loc_DFW  loc_EWR  loc_IAH  loc_JFK  \
0              92     8        0        0        0        0        0        0   
1              92     8        0        0        0        0        0        0   
2              92     8        0        0        0        0        0        0   
3              92     8        0        0        0        0        0 

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 0)
y_test.shape

(185144,)

In [0]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)



In [0]:

#logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, max_iter=1200000)
classifier.fit(x_train, y_train)


# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)

print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

print("classification report")
print(classification_report(y_test, y_pred, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn'))


[[143318   3189]
 [ 12355  26282]]
0.916043728125135
0.6802287962315915
0.8917919310508635
0.7717742409114936


In [0]:

#decision tree classifier
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)
print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

print("classification report")
print(classification_report(y_test, y_pred, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn'))


[[134255  12252]
 [ 11394  27243]]
0.872283195782742
0.7051013277428372
0.6897835169008736
0.6973583166948242


In [0]:
#random forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)
print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

print("classification report")
print(classification_report(y_test, y_pred, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn'))


[[142909   3598]
 [ 11469  27168]]
0.918620101110487
0.7031601832440407
0.8830527205356562
0.782905638084809


In [0]:
#xgboost classifier
import xgboost as xgb
from xgboost import XGBClassifier
classifier = XGBClassifier(learning_rate =0.1,n_estimators=1000,max_depth=4,min_child_weight=6,gamma=0,subsample=0.8,colsample_bytree=0.8,reg_alpha=0.005,objective= 'binary:logistic',nthread=4,scale_pos_weight=1,seed=27)
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)
print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

print("classification report")
print(classification_report(y_test, y_pred, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn'))


[[143538   2969]
 [ 11841  26796]]
0.9200082098258653
0.6935321065300101
0.9002519737947253
0.7834858629864624


In [0]:

#support vector classifier
from sklearn.linear_model import SGDClassifier 
classifier = SGDClassifier ()
classifier.fit(x_train, y_train)


# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)

print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

print("classification report")
print(classification_report(y_test, y_pred, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn'))


[[138464   8043]
 [  9598  29039]]
0.9047174091517953
0.7515852680073505
0.7831023137910577
0.7670201666688679


oversampling the data

In [37]:
rus = RandomOverSampler(random_state=42)
x_new, y_new = rus.fit_resample(x_train,y_train)
x_new.shape

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


(2633736, 38)

In [45]:

#Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, max_iter=1200000)
classifier.fit(x_new, y_new)


# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)

print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

print("classification report")
print(classification_report(y_test, y_pred, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn'))


[[135265  11242]
 [  8493  30144]]
0.8934072937821371
0.7801847969562854
0.7283622481032234
0.753383402271847
classification report
              precision    recall  f1-score   support

         0.0       0.94      0.92      0.93    146507
         1.0       0.73      0.78      0.75     38637

    accuracy                           0.89    185144
   macro avg       0.83      0.85      0.84    185144
weighted avg       0.90      0.89      0.89    185144



In [39]:

#decision tree classifier
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_new, y_new)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)
print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

print("classification report")
print(classification_report(y_test, y_pred, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn'))


[[134610  11897]
 [ 11394  27243]]
0.8742006222183814
0.7051013277428372
0.696039856923863
0.7005412911271971
classification report
              precision    recall  f1-score   support

         0.0       0.92      0.92      0.92    146507
         1.0       0.70      0.71      0.70     38637

    accuracy                           0.87    185144
   macro avg       0.81      0.81      0.81    185144
weighted avg       0.87      0.87      0.87    185144



undersampling the data


In [40]:
rus = RandomUnderSampler(random_state=42)
x_new1, y_new1 = rus.fit_resample(x_train, y_train)
x_new.shape

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


(2633736, 38)

In [46]:

#logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, max_iter=1200000)
classifier.fit(x_new1, y_new1)


# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)

print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

print("classification report")
print(classification_report(y_test, y_pred, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn'))


[[135352  11155]
 [  8514  30123]]
0.8937637730631293
0.7796412764966224
0.7297591937593876
0.7538759932428205
classification report
              precision    recall  f1-score   support

         0.0       0.94      0.92      0.93    146507
         1.0       0.73      0.78      0.75     38637

    accuracy                           0.89    185144
   macro avg       0.84      0.85      0.84    185144
weighted avg       0.90      0.89      0.90    185144



In [42]:

#decision tree classifier
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_new1, y_new1)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
v=accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)
print(v)
print(recall_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(precision_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))
print(f1_score(y_test, y_pred, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn'))

print("classification report")
print(classification_report(y_test, y_pred, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn'))


[[116714  29793]
 [  7530  31107]]
0.7984109665989716
0.8051090923208324
0.5107881773399015
0.6250339069893607
classification report
              precision    recall  f1-score   support

         0.0       0.94      0.80      0.86    146507
         1.0       0.51      0.81      0.63     38637

    accuracy                           0.80    185144
   macro avg       0.73      0.80      0.74    185144
weighted avg       0.85      0.80      0.81    185144

